# Single Ticker Search Static Data
make sure to run the below imports before continuing

In [1]:
import yfinance as fyf
import pandas as pd
from pandas_datareader import data as pdr
import numpy as np
from datetime import date
from bs4 import BeautifulSoup
import requests
from configinfo import client_id

/opt/anaconda3/lib/python3.7/site-packages/pandas_datareader/compat/__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal

## Grabbing OHLC from Yahoo Finance till the given date of the request

In [2]:
Today = date.today()
print(Today) # check for current date

def grab_OHLC_to_csv(ticker):
    filename = '/Users/jaspertsai/Desktop/Jupyter/Data/OHLC/'+ticker+'_ohlc.csv'
    data = pdr.get_data_yahoo(ticker,start = '1950-1-1', end = Today)
    data.dropna(inplace = True)
    data.to_csv(filename,index = True)

2020-12-18

### Enter the Ticker Below

In [3]:
grab_OHLC_to_csv('AAPL')

----

## Calculating Volitility and Overwrite the csv file created previously

In [4]:
def calc_Vol(ticker):
    filename = '/Users/jaspertsai/Desktop/Jupyter/Data/OHLC/'+ticker+'_ohlc.csv' #get the filename
    File = pd.read_csv(filename)  #get the file
    File['Volatility'] = File['Adj Close'].rolling(window = 30, center= False).std()*np.sqrt(252)
    File.to_csv(filename,index = True) # replacing the previous file.
    return File

### Enter the Ticker Below
(Must be one you did previously)

In [5]:
calc_Vol('AAPL')

,Date,High,Low,Open,Close,Volume,Adj Close,Volatility
0,1980-12-12,0.128906,0.128348,0.128348,0.128348,469033600.0,0.101087,NaN
1,1980-12-15,0.122210,0.121652,0.122210,0.121652,175884800.0,0.095813,NaN
2,1980-12-16,0.113281,0.112723,0.113281,0.112723,105728000.0,0.088780,NaN
3,1980-12-17,0.116071,0.115513,0.115513,0.115513,86441600.0,0.090978,NaN
4,1980-12-18,0.119420,0.118862,0.118862,0.118862,73449600.0,0.093615,NaN
...,...,...,...,...,...,...,...,...
10086,2020-12-14,123.349998,121.540001,122.599998,121.779999,79184500.0,121.779999,61.370883
10087,2020-12-15,127.900002,124.129997,124.339996,127.879997,157572300.0,127.879997,58.881473
10088,2020-12-16,128.369995,126.559998,127.410004,127.809998,98208600.0,127.809998,57.016272
10089,2020-12-17,129.580002,128.039993,128.899994,128.699997,94215500.0,128.699997,60.045058
10090,2020-12-18,129.100006,126.120003,128.960007,126.389999,100784707.0,126.389999,62.180885

----

## Grabbing Earning Historical Data

In [6]:
def grab_historical_EPS(ticker):
    source = pd.read_html('https://www.macrotrends.net/stocks/charts/'+ ticker + '/' + ticker +'/pe-ratio') #source of the ticker
    #type(source) #check source type 'list'
    df = source[0]   #grabbing the table directly
    filename = '/Users/jaspertsai/Desktop/Jupyter/Data/Earnings/'+ticker+'_eps.csv'  #save location
    df.dropna(inplace = True) #get rid of NaN
    df.to_csv(filename,index = False,header=["Date", "Stock_Price", "TTM_Net_EPS", "PE_Ratio"]) #covert dataframe to csv
    
    #reading the data back in to sort
    data = pd.read_csv('/Users/jaspertsai/Desktop/Jupyter/Data/Earnings/'+ticker+'_eps.csv') #reading back the data
    data['Date'] = pd.to_datetime(data['Date']) #coverting table str to "dates" to be able to sort
    data = data.sort_values(by="Date") #sorting
    data.to_csv(filename,index = False)
    
    return data

#fix redundant code later.

### Enter the Ticker Below
(Must be one you did previously)

In [7]:
grab_historical_EPS('AAPL')

         Date  Stock_Price TTM_Net_EPS  PE_Ratio
55 2006-12-31         2.61       $0.10     26.61
54 2007-03-31         2.86       $0.11     25.69
53 2007-06-30         3.76       $0.12     30.17
52 2007-09-30         4.73       $0.14     34.11
51 2007-12-31         6.10       $0.16     37.88
50 2008-03-31         4.42       $0.17     25.63
49 2008-06-30         5.16       $0.18     28.26
48 2008-09-30         3.50       $0.19     18.29
47 2008-12-31         2.63       $0.22     12.01
46 2009-03-31         3.24       $0.24     13.35
45 2009-06-30         4.39       $0.25     17.68
44 2009-09-30         5.71       $0.27     21.29
43 2009-12-31         6.49       $0.31     20.99
42 2010-03-31         7.24       $0.36     19.93
41 2010-06-30         7.75       $0.44     17.59
40 2010-09-30         8.74       $0.54     16.15
39 2010-12-31         9.94       $0.64     15.54
38 2011-03-31        10.74       $0.75     14.33
37 2011-06-30        10.34       $0.90     11.46
36 2011-09-30        11.75       $0.99     11.89
35 2011-12-31        12.48       $1.25      9.95
34 2012-03-31        18.47       $1.46     12.61
33 2012-06-30        17.99       $1.52     11.84
32 2012-09-30        20.64       $1.58     13.09
31 2012-12-31        16.54       $1.58     10.50
30 2013-03-31        13.84       $1.50      9.25
29 2013-06-30        12.48       $1.43      8.73
28 2013-09-30        15.10       $1.42     10.67
27 2013-12-31        17.88       $1.44     12.41
26 2014-03-31        17.20       $1.49     11.51
25 2014-06-30        20.97       $1.55     13.55
24 2014-09-30        22.84       $1.61     14.21
23 2014-12-31        25.14       $1.86     13.55
22 2015-03-31        28.45       $2.02     14.06
21 2015-06-30        28.79       $2.17     13.30
20 2015-09-30        25.35       $2.30     11.02
19 2015-12-31        24.38       $2.36     10.35
18 2016-03-31        25.38       $2.25     11.29
17 2016-06-30        22.40       $2.14     10.47
16 2016-09-30        26.63       $2.07     12.88
15 2016-12-31        27.42       $2.09     13.14
14 2017-03-31        34.16       $2.14     15.98
13 2017-06-30        34.38       $2.20     15.63
12 2017-09-30        36.94       $2.30     16.06
11 2017-12-31        40.71       $2.43     16.74
10 2018-03-31        40.52       $2.59     15.65
9  2018-06-30        44.88       $2.76     16.28
8  2018-09-30        54.93       $2.97     18.51
7  2018-12-31        38.52       $3.04     12.67
6  2019-03-31        46.58       $2.97     15.67
5  2019-06-30        48.72       $2.93     16.62
4  2019-09-30        55.35       $2.96     18.68
3  2019-12-31        72.78       $3.17     23.00
2  2020-03-31        63.18       $3.19     19.82
1  2020-06-30        90.88       $3.29     27.64
0  2020-09-30       115.61       $3.26     35.46

 ## Match Earning per Share to the dates of the month

In [8]:
#read in OHLC
#read in earnings
#loop through columns of OHLC creating a new series with a date index.
#if market data date is less than eps date then assign EPS

def merge_OHLC_EPS(ticker):
    filepath1 = '/Users/jaspertsai/Desktop/Jupyter/Data/OHLC/'+ticker+'_ohlc.csv' #get the file to be edited
    filepath2 = '/Users/jaspertsai/Desktop/Jupyter/Data/Earnings/'+ticker+'_eps.csv' #get 2nd file
    filepath3 = '/Users/jaspertsai/Desktop/Jupyter/Data/Merged/'+ticker+'_merged.csv'
    ohlc_data = pd.read_csv(filepath1, index_col=0)  #get the Main File and set indexcolumn to 0 
    eps_data = pd.read_csv(filepath2) #get eps from fps file
    
    eps = [] #create empty array
    j = 0 #set beginning step

    for i in ohlc_data.index: #allow indexing
        while j<len(eps_data) and ohlc_data.loc[i, 'Date'] >= eps_data.loc[j, 'Date']:  #while the date of ohlc is greater than the eps date
            j += 1  #increment

        if j != 0: #checks base case
            j -= 1  #if passes use the previous

        #print(ohlc_data.loc[i, 'Date']+"  eps "+ eps_data.loc[j, 'Date'])  #print and compare
        
        eps.append(eps_data.loc[j,'TTM_Net_EPS']) # appending into empty eps file
        df_eps = pd.DataFrame(eps,columns =["EPS"]) #convert to dataframe to be able to add later
        
    ohlc_data['EPS'] = df_eps     #add EPS to the ohlc_data
    ohlc_data.to_csv(filepath3,index = False)   #create a new ohlc_data
    return ohlc_data

### Enter the Ticker Below
(Must be one you did previously)

In [9]:
merge_OHLC_EPS('AAPL')

,Date,High,Low,Open,Close,Volume,Adj Close,Volatility,EPS
0,1980-12-12,0.128906,0.128348,0.128348,0.128348,469033600.0,0.101087,NaN,$0.10
1,1980-12-15,0.122210,0.121652,0.122210,0.121652,175884800.0,0.095813,NaN,$0.10
2,1980-12-16,0.113281,0.112723,0.113281,0.112723,105728000.0,0.088780,NaN,$0.10
3,1980-12-17,0.116071,0.115513,0.115513,0.115513,86441600.0,0.090978,NaN,$0.10
4,1980-12-18,0.119420,0.118862,0.118862,0.118862,73449600.0,0.093615,NaN,$0.10
...,...,...,...,...,...,...,...,...,...
10086,2020-12-14,123.349998,121.540001,122.599998,121.779999,79184500.0,121.779999,61.370883,$3.26
10087,2020-12-15,127.900002,124.129997,124.339996,127.879997,157572300.0,127.879997,58.881473,$3.26
10088,2020-12-16,128.369995,126.559998,127.410004,127.809998,98208600.0,127.809998,57.016272,$3.26
10089,2020-12-17,129.580002,128.039993,128.899994,128.699997,94215500.0,128.699997,60.045058,$3.26
10090,2020-12-18,129.100006,126.120003,128.960007,126.389999,100784707.0,126.389999,62.180885,$3.26

## Calculating the PE ratio

In [10]:
def calc_PE(ticker):
    filename = '/Users/jaspertsai/Desktop/Jupyter/Data/Merged/'+ticker+'_merged.csv' #get the filename
    File = pd.read_csv(filename)  #get the file
    File['EPS'] = File['EPS'].str.replace('$','')
    File['EPS'] = File.EPS.astype(float)
    File['PE_ratio'] = File['Adj Close']/File['EPS']
    File.to_csv(filename,index = False) # replacing the previous file.
    return File

### Enter the Ticker Below
(Must be one you did previously)

In [11]:
calc_PE('AAPL')

,Date,High,Low,Open,Close,Volume,Adj Close,Volatility,EPS,PE_ratio
0,1980-12-12,0.128906,0.128348,0.128348,0.128348,469033600.0,0.101087,NaN,0.10,1.010867
1,1980-12-15,0.122210,0.121652,0.122210,0.121652,175884800.0,0.095813,NaN,0.10,0.958126
2,1980-12-16,0.113281,0.112723,0.113281,0.112723,105728000.0,0.088780,NaN,0.10,0.887805
3,1980-12-17,0.116071,0.115513,0.115513,0.115513,86441600.0,0.090978,NaN,0.10,0.909780
4,1980-12-18,0.119420,0.118862,0.118862,0.118862,73449600.0,0.093615,NaN,0.10,0.936150
...,...,...,...,...,...,...,...,...,...,...
10086,2020-12-14,123.349998,121.540001,122.599998,121.779999,79184500.0,121.779999,61.370883,3.26,37.355828
10087,2020-12-15,127.900002,124.129997,124.339996,127.879997,157572300.0,127.879997,58.881473,3.26,39.226993
10088,2020-12-16,128.369995,126.559998,127.410004,127.809998,98208600.0,127.809998,57.016272,3.26,39.205521
10089,2020-12-17,129.580002,128.039993,128.899994,128.699997,94215500.0,128.699997,60.045058,3.26,39.478527
10090,2020-12-18,129.100006,126.120003,128.960007,126.389999,100784707.0,126.389999,62.180885,3.26,38.769938

Testing TDAMERITRADE API

In [12]:
#client_id = 'inside configinfo'

def get_quotes(**kwargs):
    
    url = 'https://api.tdameritrade.com/v1/marketdata/quotes'
    
    params = {}
    params.update({'apikey':client_id})
    
    symbol_list = []
    
    for symbol in kwargs.get('symbol'):
        symbol_list.append(symbol)
    params.update({'symbol' : symbol_list})
    
    return requests.get(url,params=params).json()

def get_ohlc(**kwargs):
    data = get_quotes(symbol=kwargs.get('symbol'))
    for symbol in kwargs.get('symbol'):
        print(symbol)
        print(data[symbol]['openPrice'],data[symbol]['highPrice'],data[symbol]['lowPrice'],data[symbol]['closePrice'])

def get_lastPrice(**kwargs):
    data = get_quotes(symbol=kwargs.get('symbol'))
    for symbol in kwargs.get('symbol'):
        print(symbol)
        print(data[symbol]['lastPrice'])

In [13]:
print(get_quotes(symbol=['AAPL']))

{'AAPL': {'assetType': 'EQUITY', 'assetMainType': 'EQUITY', 'cusip': '037833100', 'symbol': 'AAPL', 'description': 'Apple Inc. - Common Stock', 'bidPrice': 126.46, 'bidSize': 2100, 'bidId': 'Q', 'askPrice': 126.47, 'askSize': 300, 'askId': 'V', 'lastPrice': 126.47, 'lastSize': 500, 'lastId': 'D', 'openPrice': 128.96, 'highPrice': 129.1, 'lowPrice': 126.12, 'bidTick': ' ', 'closePrice': 128.7, 'netChange': -2.23, 'totalVolume': 95751350, 'quoteTimeInLong': 1608324028726, 'tradeTimeInLong': 1608324028582, 'mark': 126.47, 'exchange': 'q', 'exchangeName': 'NASD', 'marginable': True, 'shortable': True, 'volatility': 0.0072, 'digits': 4, '52WkHigh': 137.98, '52WkLow': 53.1525, 'nAV': 0.0, 'peRatio': 39.124, 'divAmount': 0.82, 'divYield': 0.64, 'divDate': '2020-11-06 00:00:00.000', 'securityStatus': 'Normal', 'regularMarketLastPrice': 126.47, 'regularMarketLastSize': 5, 'regularMarketNetChange': -2.23, 'regularMarketTradeTimeInLong': 1608324028582, 'netPercentChangeInDouble': -1.7327, 'markChangeInDouble': -2.23, 'markPercentChangeInDouble': -1.7327, 'regularMarketPercentChangeInDouble': -1.7327, 'delayed': True}}

In [15]:
get_ohlc(symbol=['AAPL','AMD'])

AAPL
128.96 129.1 126.12 128.7
AMD
97.27 97.68 93.56 96.84

In [23]:
get_lastPrice(symbol=['AAPL'])

AAPL
126.54

Streaming Version